[package]
name = "mse-thesis-template"
version = "0.0.1"
compiler = "0.15.0"
authors = [
  "Silvan Zahno <https://github.com/tschinz>",
  "Rémi Heredero <https://github.com/Klagarge>",
  "Louis Heredero <https://github.com/LordBaryhobal>",
]
repository = "https://github.com/hes-so/MSE-thesis-template"
homepage = "https://www.hes-so.ch/master/hes-so-master/formations/engineering"
license = "MIT"
description = "A thesis template tailored to the Master of Science in engineering (MSE) program at the HES-SO."
entrypoint = "lib/lib.typ"
categories = ["thesis", "report", "paper"]
disciplines = ["engineering", "computer-science", "education"]
keywords = [
  "Thesis",
  "Report",
  "Project",
  "University",
  "HES-SO",
  "MSE",
]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
